name: Maritime News Scraper

on:
  schedule:
    - cron: '0 6,12,18 * * *'  # Run at 06:00, 12:00, and 18:00 UTC daily
  workflow_dispatch:  # Allow manual trigger

jobs:
  scrape-news:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run news scraper
      env:
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
      run: python scrape_maritime_news.py
    
    - name: Commit and push results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        git diff --staged --quiet || git commit -m "Update maritime news data - $(date '+%d/%m/%Y %H:%M')"
        git push
